### PR TITLE
obvious stuff to add as discussed in #4

### PR DESCRIPTION
**Pull request by nicferrier**
Adds alists and plists via a single dedicated function for returning lookup functions.

### CODE REVIEW

**Comment by VincentToups** [comment]
Thanks, merged!  You are the first contributor, I am pretty sure, so congrats!

**Comment by nicferrier** [comment]
By the way - as I use this (and write a test with it) I realize it will be fantastic for writing tests. The business of asserting data coming out of apis is very tedious. This is an awesome way to make it eaiser. I'm sure we could come up with good ways to further abstract this specifically for testing.

**Comment by VincentToups** [comment]
Check out the `must-match` or `!` pattern.  It is perfect for testing.

**Comment by nicferrier** [comment]
Dang it. You need to upload new version to marmalade! Desperate to start using this.

I need to port the marmalade elnode app to emacs 25. They have totally changed the packaging API. This would _massively_ help.

**Comment by nicferrier** [comment]
https://github.com/nicferrier/elnode-agenda/blob/master/tests.el has some examples of how I did testing with it. Too low level. I can't immediately see how to improve them with must-match but I'll have a think.

**Comment by VincentToups** [comment]
Ok, I'll try to get a new version on Marmalade this weekend some time.  It
is exciting to see someone besides me use this code.  We use Shadchen from
time to time in my company's Common Lisp project, but as we move to
Clojure, that is likely to slow down. I am glad you are enjoying it.

**Comment by VincentToups** [comment]
I can't seem to make Marmalade update Shadchen.  The web interface tells me
that shadchen already exists when I try to upload a new version and
marmalade-upload doesn't seem to produce an error, but I don't see the
package upgraded.

The interface on the marmalade web site doesn't seem to expose an obvious
"update this package" resource.  Any hints?

**Comment by nicferrier** [comment]
You need to bump the version if marmalade already has 1.0.

I need to make it give you a more helpful error message I guess. I'll get onto that.

**Comment by VincentToups** [comment]
I tried so bumping, but no luck.  I just need to bump the version in the
header in the el file?

**Comment by nicferrier** [comment]
Yes. 1.0.1 say. Or 1.2. Or whatever.

If it doesn't work leave it with me and I'll go test. Logging and error handling is one area where marmalade definitely needs improvement soon.

**Comment by VincentToups** [comment]
So I just checked and it tells me version 1.1 is already on marmalade,
however, the project page still lists version 1.0 and the documentation
from 1.0.

It seems that it has uploaded, but perhaps it is hitting  a cache that
hasn't been cleared.

**Comment by nicferrier** [comment]
Yep. I just tested and the new one is there. And yes, the cache doesn't refresh automatically yet. It just times out after a day or so.

Again, needs fixing and is fixable... but...

**Comment by VincentToups** [comment]
Seems like I am still seeing version as 1.0 here:
http://marmalade-repo.org/packages/shadchen

**Comment by nicferrier** [comment]
No, it's definitely 1.1 if you install it.

**Comment by VincentToups** [comment]
I see what you mean, the web interface lags behind the actual install
version.

**Comment by nicferrier** [comment]
Exactly. I can fix that... but it's not high on my list.

One thing that would be easy to do though would be to explain that on the upload page :-)

**Pull request merged**
